services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tictactoe
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  tictactoearena:
    build:
      context: .
      dockerfile: TicTacToeArena/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__Default: ""

volumes:
  pgdata:
